# Generated by Django 4.1.12 on 2024-01-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(max_length=255, verbose_name="Raison sociale"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                ("adresse", models.TextField(verbose_name="Adresse")),
                ("ville", models.CharField(max_length=255, verbose_name="Ville")),
                (
                    "code_postal",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                (
                    "informations_fiscales",
                    models.TextField(verbose_name="Informations fiscales"),
                ),
                (
                    "site_web",
                    models.URLField(
                        blank=True, null=True, verbose_name="Informations fiscales"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logo/",
                        verbose_name="Logo de l'entreprise",
                    ),
                ),
                (
                    "cachet_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cachet/",
                        verbose_name="Cachet de signature",
                    ),
                ),
            ],
        ),
    ]
