# Generated by Django 4.1.12 on 2024-01-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coreApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("telephone", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("ville", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "commission_pourcentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConditionsReglement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("A_RECEPTION_FACTURE", "À réception de la facture"),
                            (
                                "60_40_A_LA_LIVRAISON",
                                "60% à la commande, 40% à la livraison",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_societe",
                    models.CharField(
                        choices=[
                            ("Societe", "Societé"),
                            ("Particulier", "Particulier"),
                        ],
                        default="Societe",
                        max_length=20,
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(max_length=255, verbose_name="Raison sociale"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                ("adresse", models.TextField(verbose_name="Adresse")),
                ("ville", models.CharField(max_length=255, verbose_name="Ville")),
                (
                    "code_postal",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                ("pays", models.CharField(max_length=255, verbose_name="Pays")),
                ("gsm", models.CharField(max_length=20, verbose_name="GSM")),
                ("fax", models.CharField(max_length=20, verbose_name="Fax")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "site_web",
                    models.URLField(blank=True, null=True, verbose_name="Site web"),
                ),
                ("banque", models.CharField(max_length=255, verbose_name="Banque")),
                ("RIB", models.CharField(max_length=27, verbose_name="RIB")),
                (
                    "RC",
                    models.CharField(
                        max_length=27, verbose_name="RC- Registre de Commerce"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                ("ICE", models.CharField(max_length=20)),
                (
                    "IF",
                    models.CharField(max_length=20, verbose_name="Identifiant Fiscal"),
                ),
                ("solde_initial", models.DecimalField(decimal_places=2, max_digits=10)),
                ("plafond", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_initial_solde", models.DateField()),
                (
                    "conditions_reglement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.conditionsreglement",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreApp.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_societe",
                    models.CharField(
                        choices=[
                            ("Societe", "Societé"),
                            ("Particulier", "Particulier"),
                        ],
                        default="Societe",
                        max_length=20,
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(max_length=255, verbose_name="Raison sociale"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                ("adresse", models.TextField(verbose_name="Adresse")),
                ("ville", models.CharField(max_length=255, verbose_name="Ville")),
                (
                    "code_postal",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                ("pays", models.CharField(max_length=255, verbose_name="Pays")),
                ("gsm", models.CharField(max_length=20, verbose_name="GSM")),
                ("fax", models.CharField(max_length=20, verbose_name="Fax")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "site_web",
                    models.URLField(blank=True, null=True, verbose_name="Site web"),
                ),
                ("banque", models.CharField(max_length=255, verbose_name="Banque")),
                ("RIB", models.CharField(max_length=27, verbose_name="RIB")),
                (
                    "RC",
                    models.CharField(
                        max_length=27, verbose_name="RC- Registre de Commerce"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                ("ICE", models.CharField(max_length=20)),
                (
                    "IF",
                    models.CharField(max_length=20, verbose_name="Identifiant Fiscal"),
                ),
                ("solde_initial", models.DecimalField(decimal_places=2, max_digits=10)),
                ("plafond", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_initial_solde", models.DateField()),
                (
                    "conditions_reglement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.conditionsreglement",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreApp.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
