# Generated by Django 4.1.12 on 2024-01-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_client_note_fournisseur_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nom",
            field=models.CharField(max_length=255, null=True, verbose_name="Nom"),
        ),
        migrations.AddField(
            model_name="client",
            name="prenom",
            field=models.CharField(max_length=255, null=True, verbose_name="Prenom"),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="nom",
            field=models.CharField(max_length=255, null=True, verbose_name="Nom"),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="prenom",
            field=models.CharField(max_length=255, null=True, verbose_name="Prenom"),
        ),
    ]
