# Generated by Django 4.1.12 on 2024-01-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_client_nom_client_prenom_fournisseur_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="province",
            field=models.CharField(max_length=255, null=True, verbose_name="Province"),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="province",
            field=models.CharField(max_length=255, null=True, verbose_name="Province"),
        ),
    ]
