# Generated by Django 4.1.12 on 2024-01-27 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0008_client_suivi_par_fournisseur_suivi_par"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="suivi_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Suivi Par",
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="suivi_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Suivi Par",
            ),
        ),
    ]
