# Generated by Django 4.1.12 on 2024-01-27 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0009_alter_client_suivi_par_alter_fournisseur_suivi_par"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="ICE",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="IF",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Identifiant Fiscal"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="RC",
            field=models.CharField(
                blank=True,
                max_length=27,
                null=True,
                verbose_name="RC- Registre de Commerce",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="RIB",
            field=models.CharField(
                blank=True, max_length=27, null=True, verbose_name="RIB"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="banque",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Banque"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_initial_solde",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="fax",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Fax"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="gsm",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="GSM"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nom",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Informations"),
        ),
        migrations.AlterField(
            model_name="client",
            name="pays",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pays"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="plafond",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="prenom",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Prenom"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="province",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Province"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="solde_initial",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="suivi_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Suivi Par",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="ville",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ville"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="ICE",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="IF",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Identifiant Fiscal"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="RC",
            field=models.CharField(
                blank=True,
                max_length=27,
                null=True,
                verbose_name="RC- Registre de Commerce",
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="RIB",
            field=models.CharField(
                blank=True, max_length=27, null=True, verbose_name="RIB"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="banque",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Banque"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="date_initial_solde",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="fax",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Fax"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="gsm",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="GSM"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="nom",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Informations"),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="pays",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pays"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="plafond",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="prenom",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Prenom"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="province",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Province"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="solde_initial",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="suivi_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Suivi Par",
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="ville",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ville"
            ),
        ),
    ]
