# Generated by Django 4.1.12 on 2024-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0010_alter_client_ice_alter_client_if_alter_client_rc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="adresse",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Adresse"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="adresse",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Adresse"
            ),
        ),
    ]
