# Generated by Django 4.1.12 on 2024-01-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0011_alter_client_adresse_alter_fournisseur_adresse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="raison_sociale",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Raison sociale"
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="raison_sociale",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Raison sociale"
            ),
        ),
    ]
