# Generated by Django 4.1.12 on 2024-02-01 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coreApp", "0002_alter_entreprise_adresse_and_more"),
        ("contacts", "0015_client_logo_societe_fournisseur_logo_societe"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercial",
            name="entreprise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreApp.entreprise",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="ICE",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="IF",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Identifiant Fiscal"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="RC",
            field=models.CharField(
                blank=True,
                max_length=27,
                null=True,
                verbose_name="RC- Registre de Commerce",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="RIB",
            field=models.CharField(
                blank=True, max_length=27, null=True, verbose_name="RIB"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="adresse",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Adresse"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="banque",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Banque"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code postal"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="conditions_reglement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A_RECEPTION_FACTURE", "À réception de la facture"),
                    ("60_40_A_LA_LIVRAISON", "60% à la commande, 40% à la livraison"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="date_initial_solde",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="entreprise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreApp.entreprise",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="fax",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Fax"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="gsm",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="GSM"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="logo_societe",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="contacts/logos/",
                verbose_name="Logo Contact",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="nom",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Informations"),
        ),
        migrations.AddField(
            model_name="prospect",
            name="pays",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Pays"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="plafond",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="prenom",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Prenom"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="province",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Province"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="raison_sociale",
            field=models.CharField(
                default="Debug",
                max_length=255,
                unique=True,
                verbose_name="Raison sociale",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="site_web",
            field=models.URLField(blank=True, null=True, verbose_name="Site web"),
        ),
        migrations.AddField(
            model_name="prospect",
            name="solde_initial",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="suivi_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Suivi Par",
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="type_societe",
            field=models.CharField(
                choices=[("Societe", "Societé"), ("Particulier", "Particulier")],
                default="Societe",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="ville",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ville"
            ),
        ),
        migrations.AlterField(
            model_name="commercial",
            name="commission_pourcentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="commercial",
            name="prenom",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="commercial",
            name="telephone",
            field=models.CharField(max_length=15),
        ),
    ]
