# Generated by Django 4.1.12 on 2024-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0016_commercial_entreprise_prospect_ice_prospect_if_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commercial",
            name="nom",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="commercial",
            name="prenom",
            field=models.CharField(max_length=50),
        ),
    ]
