# Generated by Django 4.1.12 on 2024-01-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_entreprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
    ]
