# Generated by Django 5.0.1 on 2024-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profileImages/', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
