# Generated by Django 4.1.12 on 2024-01-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coreApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("code_barre", models.CharField(max_length=50, unique=True)),
                ("designation", models.CharField(max_length=255)),
                ("pays_dorigine", models.CharField(max_length=255)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("emplacement", models.CharField(blank=True, max_length=50, null=True)),
                ("sur_catalog", models.BooleanField(default=False)),
                ("prix_1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_ttc_1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_ttc_2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_ttc_3", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prix_achat_net",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "prix_achat_net_ttc",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "prix_achat_brut",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "prix_achat_brut_ttc",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "image_produit",
                    models.ImageField(blank=True, null=True, upload_to="produit/"),
                ),
                (
                    "tva_pourcentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "largeur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "longueur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "epaisseur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "unite_principale",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("unite_vente", models.CharField(blank=True, max_length=20, null=True)),
                ("marque", models.CharField(blank=True, max_length=50, null=True)),
                ("couleur", models.CharField(blank=True, max_length=50, null=True)),
                ("taille", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productsandservices.categorie",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="coreApp.entreprise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Remise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("P", "Pourcentage"), ("F", "Valeur Fixe")],
                        max_length=1,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="SousCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("designation", models.CharField(max_length=255)),
                ("pays_dorigine", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "prix_1",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prix_2",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prix_3",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tva_pourcentage",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                (
                    "prix_ttc_1",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prix_ttc_2",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prix_ttc_3",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prix_achat_net",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "prix_achat_pourcentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "remise_achat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="coreApp.entreprise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taux_reduction", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productsandservices.pack",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productsandservices.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
            },
        ),
        migrations.AddField(
            model_name="produit",
            name="remise_achat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productsandservices.remise",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="sous_categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="productsandservices.souscategorie",
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="produits",
            field=models.ManyToManyField(
                related_name="packs", to="productsandservices.produit"
            ),
        ),
    ]
