# Generated by Django 5.0.1 on 2024-02-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsandservices', '0002_alter_produit_categorie_alter_produit_code_barre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantité sur stock'),
        ),
    ]
