# Generated by Django 5.0.1 on 2024-02-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsandservices', '0004_alter_produit_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_1',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de Vente'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat_net',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat_net_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat TTC"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_ttc_1',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de Vente TTC'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='tva_pourcentage',
            field=models.PositiveIntegerField(default=20, verbose_name='TVA %'),
        ),
    ]
