# Generated by Django 5.0.1 on 2024-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsandservices', '0005_alter_produit_prix_1_alter_produit_prix_achat_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='tva_pourcentage',
            field=models.PositiveIntegerField(default=20, verbose_name='TVA (%)'),
        ),
    ]
