# Generated by Django 5.0 on 2024-02-15 14:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsandservices', '0008_souscategorie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='unite_principale',
        ),
        migrations.AlterField(
            model_name='produit',
            name='couleur',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pays_dorigine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Pays d'origine"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_vente',
            field=models.CharField(choices=[('Kilogram', 'Kg'), ('Gram', 'g'), ('Pound', 'lb'), ('Ounce', 'oz'), ('Liter', 'l'), ('Milliliter', 'Ml'), ('Gallon', 'gal'), ('Quart', 'qt'), ('Pack', 'pack'), ('Box', 'box'), ('Unit', 'U'), ('Other', 'autre')], default='U', max_length=20, verbose_name='Unité de vente'),
            preserve_default=False,
        ),
    ]
