# Generated by Django 5.0 on 2024-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsandservices', '0009_remove_produit_unite_principale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pays_dorigine',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prix_achat_net',
        ),
        migrations.RemoveField(
            model_name='service',
            name='prix_achat_pourcentage',
        ),
        migrations.RemoveField(
            model_name='service',
            name='remise_achat',
        ),
        migrations.AddField(
            model_name='service',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='couleur',
            field=models.CharField(blank=True, default='#7F00FF', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='designation',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais du service (Prix Principal)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_ttc_1',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_ttc_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix_ttc_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='tva_pourcentage',
            field=models.PositiveIntegerField(default=20, verbose_name='TVA (%)'),
        ),
    ]
