# Generated by Django 4.1.12 on 2024-02-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "productsandservices",
            "0011_remove_pack_description_remove_pack_produits_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="packproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="productsandservices.produit",
                verbose_name="Produit",
            ),
        ),
        migrations.AlterField(
            model_name="packproduct",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantité"),
        ),
    ]
