# Generated by Django 5.0 on 2024-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsandservices', '0012_alter_packproduct_product_alter_packproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='nom',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pack',
            name='product_data',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PackProduct',
        ),
    ]
