# Generated by Django 5.0 on 2024-02-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsandservices', '0013_rename_nom_pack_name_pack_product_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='name',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='product_data',
        ),
        migrations.CreateModel(
            name='PackProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsandservices.pack')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsandservices.produit', verbose_name='Produit')),
            ],
        ),
    ]
