# Generated by Django 4.1.12 on 2024-02-23 15:41

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        (
            "productsandservices",
            "0014_rename_name_pack_nom_remove_pack_product_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="pack",
            name="nom",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
