# Generated by Django 4.1.12 on 2024-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productsandservices", "0015_produit_tags_alter_pack_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="unite_vente",
            field=models.CharField(
                choices=[
                    ("Kilogram", "Kg"),
                    ("Gram", "g"),
                    ("Pound", "lb"),
                    ("Ounce", "oz"),
                    ("Liter", "l"),
                    ("Milliliter", "ml"),
                    ("Gallon", "gal"),
                    ("Quart", "qt"),
                    ("Pack", "pack"),
                    ("Box", "box"),
                    ("Unit", "U"),
                    ("Other", "autre"),
                ],
                max_length=20,
                verbose_name="Unité de vente",
            ),
        ),
    ]
