# Generated by Django 5.0 on 2024-02-27 11:30

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsandservices', '0016_alter_produit_unite_vente'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='nom',
            field=models.CharField(default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_vente',
            field=models.CharField(choices=[('Kilogram', 'Kg'), ('Gram', 'g'), ('Pound', 'lb'), ('Ounce', 'oz'), ('Liter', 'l'), ('Milliliter', 'ml'), ('Gallon', 'gal'), ('Quart', 'qt'), ('Pack', 'pack'), ('Box', 'box'), ('Unit', 'U'), ('Other', 'autre')], default='Unit', max_length=20, verbose_name='Unité de vente'),
        ),
    ]
