# Generated by Django 4.1.12 on 2024-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productsandservices", "0017_promotion_nom_alter_produit_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="prix_1",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix de Vente HT"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix de Vente-2 HT",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix_3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix de Vente-3 HT",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix_achat_net",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix d'achat HT"
            ),
        ),
    ]
