# Generated by Django 4.1.12 on 2024-03-29 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productsandservices", "0001_initial"),
        ("coreApp", "0002_alter_entreprise_adresse_and_more"),
        ("contacts", "0017_alter_commercial_nom_alter_commercial_prenom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avoirs",
            fields=[
                (
                    "type_remise",
                    models.CharField(
                        choices=[("FIXED", "Valeur fixe"), ("PERCENT", "Pourcentage")],
                        default="FIXED",
                        max_length=7,
                    ),
                ),
                (
                    "valeur_remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valeur Remise",
                    ),
                ),
                (
                    "status_devis",
                    models.CharField(
                        choices=[
                            ("encours", "En cours"),
                            ("expire", "Éxpiré"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("paye", "Payé"),
                        ],
                        default="encours",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("echeance", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_devis",
                    models.CharField(
                        choices=[("achat", "Achat"), ("vente", "Vente")], max_length=10
                    ),
                ),
                ("objet", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "devise",
                    models.CharField(
                        blank=True,
                        default="MAD",
                        max_length=3,
                        null=True,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "commission_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "moyen_de_paiement",
                    models.CharField(
                        choices=[
                            ("Espèce", "Espèce"),
                            ("Prélèvement", "Prélèvement"),
                            ("Chèque", "Chèque"),
                            ("Virement", "Virement"),
                            ("Versement", "Versement"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=12,
                    ),
                ),
                (
                    "adresse_de_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_livraison", models.DateField(blank=True, null=True)),
                (
                    "condition_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("document", models.FileField(upload_to="documents/bonavoirs/")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avoirs_clients",
                        to="contacts.client",
                    ),
                ),
                (
                    "condition_reglement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.conditionsreglement",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avoirs",
                        to="coreApp.entreprise",
                    ),
                ),
                (
                    "suivi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avoirs_suivi_par",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "type_remise",
                    models.CharField(
                        choices=[("FIXED", "Valeur fixe"), ("PERCENT", "Pourcentage")],
                        default="FIXED",
                        max_length=7,
                    ),
                ),
                (
                    "valeur_remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valeur Remise",
                    ),
                ),
                (
                    "status_devis",
                    models.CharField(
                        choices=[
                            ("encours", "En cours"),
                            ("expire", "Éxpiré"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("paye", "Payé"),
                        ],
                        default="encours",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("echeance", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_devis",
                    models.CharField(
                        choices=[("achat", "Achat"), ("vente", "Vente")], max_length=10
                    ),
                ),
                ("objet", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "devise",
                    models.CharField(
                        blank=True,
                        default="MAD",
                        max_length=3,
                        null=True,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "commission_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "moyen_de_paiement",
                    models.CharField(
                        choices=[
                            ("Espèce", "Espèce"),
                            ("Prélèvement", "Prélèvement"),
                            ("Chèque", "Chèque"),
                            ("Virement", "Virement"),
                            ("Versement", "Versement"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=12,
                    ),
                ),
                (
                    "adresse_de_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_livraison", models.DateField(blank=True, null=True)),
                (
                    "condition_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("document", models.FileField(upload_to="documents/bondecommande/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "type_remise",
                    models.CharField(
                        choices=[("FIXED", "Valeur fixe"), ("PERCENT", "Pourcentage")],
                        default="FIXED",
                        max_length=7,
                    ),
                ),
                (
                    "valeur_remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valeur Remise",
                    ),
                ),
                (
                    "status_devis",
                    models.CharField(
                        choices=[
                            ("encours", "En cours"),
                            ("expire", "Éxpiré"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("paye", "Payé"),
                        ],
                        default="encours",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("echeance", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_devis",
                    models.CharField(
                        choices=[("achat", "Achat"), ("vente", "Vente")], max_length=10
                    ),
                ),
                ("objet", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "devise",
                    models.CharField(
                        blank=True,
                        default="MAD",
                        max_length=3,
                        null=True,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "commission_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "moyen_de_paiement",
                    models.CharField(
                        choices=[
                            ("Espèce", "Espèce"),
                            ("Prélèvement", "Prélèvement"),
                            ("Chèque", "Chèque"),
                            ("Virement", "Virement"),
                            ("Versement", "Versement"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=12,
                    ),
                ),
                (
                    "adresse_de_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_livraison", models.DateField(blank=True, null=True)),
                (
                    "condition_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numero", models.IntegerField(unique=True)),
                ("document", models.FileField(upload_to="documents/devisdevente/")),
                (
                    "bon_de_commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bon_de_commande",
                        to="transactions.commande",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devis_clients",
                        to="contacts.client",
                    ),
                ),
                (
                    "commercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercial_devis_vente",
                        to="contacts.commercial",
                    ),
                ),
                (
                    "condition_reglement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.conditionsreglement",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devis_vente",
                        to="coreApp.entreprise",
                    ),
                ),
                (
                    "suivi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devis_suivi_par",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "type_remise",
                    models.CharField(
                        choices=[("FIXED", "Valeur fixe"), ("PERCENT", "Pourcentage")],
                        default="FIXED",
                        max_length=7,
                    ),
                ),
                (
                    "valeur_remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valeur Remise",
                    ),
                ),
                (
                    "status_devis",
                    models.CharField(
                        choices=[
                            ("encours", "En cours"),
                            ("expire", "Éxpiré"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("paye", "Payé"),
                        ],
                        default="encours",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("echeance", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_devis",
                    models.CharField(
                        choices=[("achat", "Achat"), ("vente", "Vente")], max_length=10
                    ),
                ),
                ("objet", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "devise",
                    models.CharField(
                        blank=True,
                        default="MAD",
                        max_length=3,
                        null=True,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "commission_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "moyen_de_paiement",
                    models.CharField(
                        choices=[
                            ("Espèce", "Espèce"),
                            ("Prélèvement", "Prélèvement"),
                            ("Chèque", "Chèque"),
                            ("Virement", "Virement"),
                            ("Versement", "Versement"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=12,
                    ),
                ),
                (
                    "adresse_de_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_livraison", models.DateField(blank=True, null=True)),
                (
                    "condition_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("document", models.FileField(upload_to="documents/factures/")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facture_clients",
                        to="contacts.client",
                    ),
                ),
                (
                    "commercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercial_facture_vente",
                        to="contacts.commercial",
                    ),
                ),
                (
                    "condition_reglement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.conditionsreglement",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="coreApp.entreprise",
                    ),
                ),
                (
                    "suivi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures_suivi_par",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "type_remise",
                    models.CharField(
                        choices=[("FIXED", "Valeur fixe"), ("PERCENT", "Pourcentage")],
                        default="FIXED",
                        max_length=7,
                    ),
                ),
                (
                    "valeur_remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valeur Remise",
                    ),
                ),
                (
                    "status_devis",
                    models.CharField(
                        choices=[
                            ("encours", "En cours"),
                            ("expire", "Éxpiré"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("paye", "Payé"),
                        ],
                        default="encours",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("echeance", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_devis",
                    models.CharField(
                        choices=[("achat", "Achat"), ("vente", "Vente")], max_length=10
                    ),
                ),
                ("objet", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "devise",
                    models.CharField(
                        blank=True,
                        default="MAD",
                        max_length=3,
                        null=True,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "commission_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "moyen_de_paiement",
                    models.CharField(
                        choices=[
                            ("Espèce", "Espèce"),
                            ("Prélèvement", "Prélèvement"),
                            ("Chèque", "Chèque"),
                            ("Virement", "Virement"),
                            ("Versement", "Versement"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=12,
                    ),
                ),
                (
                    "adresse_de_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_livraison", models.DateField(blank=True, null=True)),
                (
                    "condition_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("document", models.FileField(upload_to="documents/bondelivraison/")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraison_clients",
                        to="contacts.client",
                    ),
                ),
                (
                    "commercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commercial_livraison_vente",
                        to="contacts.commercial",
                    ),
                ),
                (
                    "condition_reglement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.conditionsreglement",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraisons",
                        to="coreApp.entreprise",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facture",
                        to="transactions.facture",
                    ),
                ),
                (
                    "suivi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraisons_suivi_par",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Purchases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Retour",
            fields=[
                (
                    "type_remise",
                    models.CharField(
                        choices=[("FIXED", "Valeur fixe"), ("PERCENT", "Pourcentage")],
                        default="FIXED",
                        max_length=7,
                    ),
                ),
                (
                    "valeur_remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valeur Remise",
                    ),
                ),
                (
                    "status_devis",
                    models.CharField(
                        choices=[
                            ("encours", "En cours"),
                            ("expire", "Éxpiré"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("paye", "Payé"),
                        ],
                        default="encours",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("echeance", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_devis",
                    models.CharField(
                        choices=[("achat", "Achat"), ("vente", "Vente")], max_length=10
                    ),
                ),
                ("objet", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "devise",
                    models.CharField(
                        blank=True,
                        default="MAD",
                        max_length=3,
                        null=True,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "commission_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "moyen_de_paiement",
                    models.CharField(
                        choices=[
                            ("Espèce", "Espèce"),
                            ("Prélèvement", "Prélèvement"),
                            ("Chèque", "Chèque"),
                            ("Virement", "Virement"),
                            ("Versement", "Versement"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=12,
                    ),
                ),
                (
                    "adresse_de_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_livraison", models.DateField(blank=True, null=True)),
                (
                    "condition_livraison",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("numero", models.AutoField(primary_key=True, serialize=False)),
                ("document", models.FileField(upload_to="documents/bonderetour/")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retour_clients",
                        to="contacts.client",
                    ),
                ),
                (
                    "condition_reglement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.conditionsreglement",
                    ),
                ),
                (
                    "suivi_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retours_suivi_par",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avoirs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avoirs_vente",
                        to="transactions.avoirs",
                    ),
                ),
                (
                    "commandes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes_vente",
                        to="transactions.commande",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devis_vente",
                        to="transactions.devis",
                    ),
                ),
                (
                    "factures",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures_vente",
                        to="transactions.facture",
                    ),
                ),
                (
                    "livraisons",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraisons_vente",
                        to="transactions.livraison",
                    ),
                ),
                (
                    "retours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retours_vente",
                        to="transactions.retour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneRetour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                ("montant_tva", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ht", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ttc", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "remise",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_retour",
                        to="transactions.retour",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LigneLivraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                ("montant_tva", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ht", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ttc", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "remise",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "livraison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_livraison",
                        to="transactions.livraison",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LigneFacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                ("montant_tva", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ht", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ttc", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "remise",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "marge_beneficiaire",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_facture",
                        to="transactions.facture",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LigneDevis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                ("montant_tva", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ht", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ttc", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "remise",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix HT"
                    ),
                ),
                (
                    "unit_price_ttc",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix TTC"
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_devis",
                        to="transactions.devis",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productsandservices.produit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                ("montant_tva", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ht", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ttc", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "remise",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_commande",
                        to="transactions.commande",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LigneAvoirs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
                ),
                ("montant_tva", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ht", models.DecimalField(decimal_places=3, max_digits=10)),
                ("montant_ttc", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "remise",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "avoir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_avoirs",
                        to="transactions.avoirs",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="bon_de_livraison",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bon_de_livraison",
                to="transactions.livraison",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="client",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commande_clients",
                to="contacts.client",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="commercial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commercial_commande_vente",
                to="contacts.commercial",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="condition_reglement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.conditionsreglement",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commande",
                to="coreApp.entreprise",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="suivi_par",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes_suivi_par",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
