# Generated by Django 4.1.12 on 2024-03-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "productsandservices",
            "0018_alter_produit_prix_1_alter_produit_prix_2_and_more",
        ),
        ("contacts", "0017_alter_commercial_nom_alter_commercial_prenom"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avoirs",
            name="delai_livraison",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="delai_livraison",
        ),
        migrations.RemoveField(
            model_name="devis",
            name="delai_livraison",
        ),
        migrations.RemoveField(
            model_name="facture",
            name="delai_livraison",
        ),
        migrations.RemoveField(
            model_name="livraison",
            name="delai_livraison",
        ),
        migrations.RemoveField(
            model_name="retour",
            name="delai_livraison",
        ),
        migrations.AddField(
            model_name="avoirs",
            name="condition_reglement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.conditionsreglement",
            ),
        ),
        migrations.AddField(
            model_name="avoirs",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="avoirs",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="avoirs",
            name="moyen_de_paiement",
            field=models.CharField(
                choices=[
                    ("Espèce", "Espèce"),
                    ("Prélèvement", "Prélèvement"),
                    ("Chèque", "Chèque"),
                    ("Virement", "Virement"),
                    ("Versement", "Versement"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="condition_reglement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.conditionsreglement",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="moyen_de_paiement",
            field=models.CharField(
                choices=[
                    ("Espèce", "Espèce"),
                    ("Prélèvement", "Prélèvement"),
                    ("Chèque", "Chèque"),
                    ("Virement", "Virement"),
                    ("Versement", "Versement"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="condition_reglement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.conditionsreglement",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="moyen_de_paiement",
            field=models.CharField(
                choices=[
                    ("Espèce", "Espèce"),
                    ("Prélèvement", "Prélèvement"),
                    ("Chèque", "Chèque"),
                    ("Virement", "Virement"),
                    ("Versement", "Versement"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="condition_reglement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.conditionsreglement",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facture",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="moyen_de_paiement",
            field=models.CharField(
                choices=[
                    ("Espèce", "Espèce"),
                    ("Prélèvement", "Prélèvement"),
                    ("Chèque", "Chèque"),
                    ("Virement", "Virement"),
                    ("Versement", "Versement"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="lignedevis",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="productsandservices.produit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lignedevis",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lignedevis",
            name="total_ht",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total HT",
            ),
        ),
        migrations.AddField(
            model_name="lignedevis",
            name="total_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total TTC",
            ),
        ),
        migrations.AddField(
            model_name="lignedevis",
            name="unit_price_ht",
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=10, verbose_name="Prix HT"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lignedevis",
            name="unit_price_ttc",
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=10, verbose_name="Prix TTC"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livraison",
            name="condition_reglement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.conditionsreglement",
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livraison",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="moyen_de_paiement",
            field=models.CharField(
                choices=[
                    ("Espèce", "Espèce"),
                    ("Prélèvement", "Prélèvement"),
                    ("Chèque", "Chèque"),
                    ("Virement", "Virement"),
                    ("Versement", "Versement"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="retour",
            name="condition_reglement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.conditionsreglement",
            ),
        ),
        migrations.AddField(
            model_name="retour",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="retour",
            name="devise",
            field=models.CharField(
                blank=True,
                default="MAD",
                max_length=3,
                null=True,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="retour",
            name="moyen_de_paiement",
            field=models.CharField(
                choices=[
                    ("Espèce", "Espèce"),
                    ("Prélèvement", "Prélèvement"),
                    ("Chèque", "Chèque"),
                    ("Virement", "Virement"),
                    ("Versement", "Versement"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="lignedevis",
            name="reference",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
