# Generated by Django 4.1.12 on 2024-04-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avoirs",
            name="note",
            field=models.TextField(default="Aucune"),
        ),
        migrations.AddField(
            model_name="commande",
            name="note",
            field=models.TextField(default="Aucune"),
        ),
        migrations.AddField(
            model_name="devis",
            name="note",
            field=models.TextField(default="Aucune"),
        ),
        migrations.AddField(
            model_name="facture",
            name="note",
            field=models.TextField(default="Aucune"),
        ),
        migrations.AddField(
            model_name="livraison",
            name="note",
            field=models.TextField(default="Aucune"),
        ),
        migrations.AddField(
            model_name="retour",
            name="note",
            field=models.TextField(default="Aucune"),
        ),
    ]
