# Generated by Django 5.0 on 2024-03-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
