# Generated by Django 5.0 on 2024-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_devis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoirs',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='retour',
            name='remise',
        ),
        migrations.AddField(
            model_name='avoirs',
            name='type_remise',
            field=models.CharField(choices=[('FIXED', 'Valeur fixe'), ('PERCENT', 'Pourcentage')], default='FIXED', help_text='Select the type of discount', max_length=7),
        ),
        migrations.AddField(
            model_name='avoirs',
            name='valeur_remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the value of the discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_remise',
            field=models.CharField(choices=[('FIXED', 'Valeur fixe'), ('PERCENT', 'Pourcentage')], default='FIXED', help_text='Select the type of discount', max_length=7),
        ),
        migrations.AddField(
            model_name='commande',
            name='valeur_remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the value of the discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_remise',
            field=models.CharField(choices=[('FIXED', 'Valeur fixe'), ('PERCENT', 'Pourcentage')], default='FIXED', help_text='Select the type of discount', max_length=7),
        ),
        migrations.AddField(
            model_name='devis',
            name='valeur_remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the value of the discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_remise',
            field=models.CharField(choices=[('FIXED', 'Valeur fixe'), ('PERCENT', 'Pourcentage')], default='FIXED', help_text='Select the type of discount', max_length=7),
        ),
        migrations.AddField(
            model_name='facture',
            name='valeur_remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the value of the discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='livraison',
            name='type_remise',
            field=models.CharField(choices=[('FIXED', 'Valeur fixe'), ('PERCENT', 'Pourcentage')], default='FIXED', help_text='Select the type of discount', max_length=7),
        ),
        migrations.AddField(
            model_name='livraison',
            name='valeur_remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the value of the discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='retour',
            name='type_remise',
            field=models.CharField(choices=[('FIXED', 'Valeur fixe'), ('PERCENT', 'Pourcentage')], default='FIXED', help_text='Select the type of discount', max_length=7),
        ),
        migrations.AddField(
            model_name='retour',
            name='valeur_remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the value of the discount', max_digits=10),
        ),
    ]
